Loading cache...done.
Loaded 1825 entries from dependency cache.
Parsing recipes...done.
Parsing of 1043 .bb files complete (1041 cached, 2 parsed). 1828 targets, 237 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.42.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "powerpc-deby-linux"
MACHINE              = "qemuppc"
DISTRO               = "deby-tiny"
DISTRO_VERSION       = "10.0"
TUNE_FEATURES        = "m32 fpu-hard ppc7400 altivec"
TARGET_FPU           = ""
meta                 
meta-poky            = "warrior:79a850a10a4b88a6d20d607b322542f947874323"
meta-debian          = "warrior:fda6a80e4cae9aa03f502551f35fe41beb7bb944"

Initialising tasks...done.
Sstate summary: Wanted 9 Found 0 Missed 9 Current 122 (0% match, 93% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Running task 598 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_fetch)
NOTE: Running task 725 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python_debian.bb:do_package)
NOTE: recipe python-setuptools-40.8.0-r0: task do_fetch: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_fetch: Succeeded
NOTE: Running task 726 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_unpack)
NOTE: Running task 736 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_prepare_recipe_sysroot)
NOTE: recipe python-setuptools-40.8.0-r0: task do_unpack: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_prepare_recipe_sysroot: Started
NOTE: recipe python-2.7.16-r0: task do_package: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_unpack: Succeeded
NOTE: Running task 753 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_debian_unpack_extra)
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_unpack_extra: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_unpack_extra: Succeeded
NOTE: Running task 754 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_debian_patch)
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_patch: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_prepare_recipe_sysroot: Succeeded
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_patch: Succeeded
NOTE: Running task 755 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_patch)
NOTE: recipe python-setuptools-40.8.0-r0: task do_patch: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_patch: Succeeded
NOTE: Running task 756 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_configure)
NOTE: Running task 757 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_populate_lic)
NOTE: recipe python-setuptools-40.8.0-r0: task do_configure: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_lic: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_lic: Succeeded
NOTE: recipe python-setuptools-40.8.0-r0: task do_configure: Succeeded
NOTE: Running task 758 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_compile)
NOTE: recipe python-setuptools-40.8.0-r0: task do_compile: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_compile: Succeeded
NOTE: Running task 759 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_install)
NOTE: recipe python-setuptools-40.8.0-r0: task do_install: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_install: Succeeded
NOTE: Running task 760 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_populate_sysroot)
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_sysroot: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_sysroot: Succeeded
ERROR: python-2.7.16-r0 do_package: QA Issue: python: Files/directories were installed but not shipped in any package:
  /usr/lib/powerpc-linux-gnu
  /usr/lib/powerpc-linux-gnu/pkgconfig
  /usr/lib/powerpc-linux-gnu/pkgconfig/python-2.7.pc
  /usr/lib/powerpc-linux-gnu/pkgconfig/python2.pc
  /usr/lib/powerpc-linux-gnu/pkgconfig/python.pc
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
python: 5 installed and not shipped files. [installed-vs-shipped]
ERROR: python-2.7.16-r0 do_package: Fatal QA errors found, failing task.
ERROR: python-2.7.16-r0 do_package: 
ERROR: python-2.7.16-r0 do_package: Function failed: do_package
ERROR: Logfile of failure stored in: /home/deby/build-tiny/tmp/work/ppc7400-deby-linux/python/2.7.16-r0/temp/log.do_package.20604
NOTE: recipe python-2.7.16-r0: task do_package: Failed
ERROR: Task (/home/deby/poky/meta-debian/recipes-debian/python/python_debian.bb:do_package) failed with exit code '1'
NOTE: Tasks Summary: Attempted 760 tasks of which 748 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/deby/poky/meta-debian/recipes-debian/python/python_debian.bb:do_package
Summary: There were 4 ERROR messages shown, returning a non-zero exit code.
